version: '2.1'

services:
  mysqld:
    image: mysql/mysql-server:5.7.18-1.0.0
    volumes:
      - ./my.cnf:/etc/my.cnf:ro
      - .:/work
    environment:
#     MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#     MYSQL_ONETIME_PASSWORD: "yes"
#     MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
