version: '2.1'

services:
  mysqld:
    image: ${IMAGE:-mysql}
    container_name: mysqld
    volumes:
      - .:/work
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --local-infile=1

