SELECT @@session.sql_mode;
DROP DATABASE IF EXISTS bar;
CREATE DATABASE bar DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
use `bar`;
CREATE TABLE ip (
        id INTEGER UNSIGNED NOT NULL, 
        addr VARCHAR(191) NOT NULL, 
        PRIMARY KEY (id)
)CHARSET=utf8mb4 ENGINE=InnoDB;
BEGIN;
LOAD DATA LOCAL INFILE '/work/LOAD.sql' INTO TABLE `ip` FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\' LINES TERMINATED BY '\n' (`id`, `addr`);
SHOW WARNINGS\G;
COMMIT;
BEGIN;
SELECT * FROM ip \G;
/* INSERT INTO ip (`id`, `addr`) VALUES (2, '192.168.0.2'); */
UPDATE ip SET addr='192.168.0.1' WHERE id = 1;
SHOW WARNINGS\G;
SELECT * FROM ip \G;
COMMIT;
