DROP DATABASE IF EXISTS bar;
CREATE DATABASE bar DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
use `bar`;
CREATE TABLE ip (
        id INTEGER UNSIGNED NOT NULL, 
        addr VARCHAR(191) NOT NULL, 
        PRIMARY KEY (id)
)CHARSET=utf8mb4 ENGINE=InnoDB;
BEGIN;
LOAD DATA LOCAL INFILE '/work/LOAD.sql' INTO TABLE `ip` FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\' LINES TERMINATED BY '\n' (`id`, `addr`);
SHOW WARNINGS\G;
COMMIT;
