version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: running test 
          command: |
            set -x
            while read file; do
              case ${file} in
                docker-compose.yml)
                  docker-compose up -d 
                  # docker-compose bug 
                  # https://github.com/docker/compose/issues/3352
                  #  -T option disabled stdin and tty
                  #  We needs stdin and no tty option.
                  docker-compose exec mysqld sh -c 'mysql -e "select version()";mysql </work/error.sql'
                  docker-compose down
                  ;;  
                docker-compose-oracle-image.yml)
                  docker-compose -f docker-compose-oracle-image.yml up -d 
                  docker-compose exec mysqld sh -c 'mysql -e "select version()";mysql </work/error.sql'
                  docker-compose down
                  ;;
                *)
                  echo "No task.(target file ${file})"
                  ;;
              esac
            done < <(git diff --name-only master..${CIRCLE_BRANCH})
