version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: running test 
          command: |
            make all
            # docker-compose bug 
            # https://github.com/docker/compose/issues/3352
            #  -T option disabled stdin and tty
            #  We needs stdin and no tty option.
            make all-rep
